version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-36
      - test-37
      - test-38
      - test-39
jobs:
  test-36: &test-template
    docker:
      - image: circleci/python:3.6.14
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            virtualenv venv
            . venv/bin/activate
            mkdir test-results
      - run:
          name: Install swprepost and dependencies
          command: |
            . venv/bin/activate
            pip install -e .[dev]
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            cd test
            coverage run --source=../swprepost --omit=*/testtools.py,*/test_*.py -m unittest
      - run:
          name: Create coverage xml
          command: |
            . venv/bin/activate
            mv test/.coverage test-results
            cd test-results
            coverage xml -o coverage.xml
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
      - run:
          name: Call Codecov
          command: |
            . venv/bin/activate
            pip install codecov
            codecov

  test-37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.11
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-38:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.11
        auth:
          username: jpvantassel
          password: $DOCKER_PASS

  test-39:
    <<: *test-template
    docker:
      - image: circleci/python:3.9.6
        auth:
          username: jpvantassel
          password: $DOCKER_PASS
